import { useEffect, useState } from "react";
import { getAlerts } from "./services/api";

type Props = {
  language?: "es" | "en";
};

type Alerta = {
  id: number;
  title: string;
  body?: string;
  priority: "high" | "medium" | "low" | string;
};

function Alertas({ language = "es" }: Props) {
  const [alertas, setAlertas] = useState<Alerta[]>([]);

  const text = {
    es: {
      headerTag: "Centro de alertas",
      title: "🚨 Alertas inteligentes",
      description:
        "Eventos críticos detectados por los agentes competitivos y el sistema de monitoreo.",
      refresh: "🔄 Actualizar",
      export: "📥 Exportar JSON",
      criticalAlerts: "Alertas críticas",
      criticalDesc: "Requieren revisión inmediata.",
      totalAlerts: "Total alertas",
      totalDesc: "Detectadas por el backend FastAPI.",
      systemStatus: "Estado sistema",
      active: "Activo",
      systemDesc: "Monitoreo funcionando correctamente.",
      lastUpdate: "Última actualización",
      minutes: "2 min",
      syncDesc: "Información sincronizada en tiempo real.",
      consoleTitle: "📡 Consola operacional",
      consoleDesc: "Eventos generados automáticamente desde backend.",
      noDescription: "Sin descripción disponible",
      generated: "Generado por sistema IA · Hace 5 min",
      review: "Revisar",
      fileName: "alertas_encintel.json",
    },
    en: {
      headerTag: "Alert Center",
      title: "🚨 Smart Alerts",
      description:
        "Critical events detected by competitive agents and the monitoring system.",
      refresh: "🔄 Refresh",
      export: "📥 Export JSON",
      criticalAlerts: "Critical alerts",
      criticalDesc: "Require immediate review.",
      totalAlerts: "Total alerts",
      totalDesc: "Detected by the FastAPI backend.",
      systemStatus: "System status",
      active: "Active",
      systemDesc: "Monitoring is running correctly.",
      lastUpdate: "Last update",
      minutes: "2 min",
      syncDesc: "Information synchronized in real time.",
      consoleTitle: "📡 Operational console",
      consoleDesc: "Events automatically generated from backend.",
      noDescription: "No description available",
      generated: "Generated by AI system · 5 min ago",
      review: "Review",
      fileName: "alerts_encintel.json",
    },
  };

  const t = text[language];

  useEffect(() => {
    getAlerts().then((data) => {
      setAlertas(data);
    });
  }, []);

  const exportarJSON = () => {
    const dataStr =
      "data:text/json;charset=utf-8," +
      encodeURIComponent(JSON.stringify(alertas, null, 2));

    const downloadAnchor = document.createElement("a");
    downloadAnchor.setAttribute("href", dataStr);
    downloadAnchor.setAttribute("download", t.fileName);

    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
  };

  return (
    <main className="main">
      <section className="page-header-pro">
        <div>
          <span>{t.headerTag}</span>
          <h1>{t.title}</h1>
          <p>{t.description}</p>
        </div>

        <div className="page-actions">
          <button className="btn-light" onClick={() => window.location.reload()}>
            {t.refresh}
          </button>

          <button className="btn-main" onClick={exportarJSON}>
            {t.export}
          </button>
        </div>
      </section>

      <section className="executive-grid">
        <div className="executive-card alert-card">
          <span>{t.criticalAlerts}</span>
          <h2>{alertas.filter((a) => a.priority === "high").length}</h2>
          <p>{t.criticalDesc}</p>
        </div>

        <div className="executive-card">
          <span>{t.totalAlerts}</span>
          <h2>{alertas.length}</h2>
          <p>{t.totalDesc}</p>
        </div>

        <div className="executive-card">
          <span>{t.systemStatus}</span>
          <h2>{t.active}</h2>
          <p>{t.systemDesc}</p>
        </div>

        <div className="executive-card">
          <span>{t.lastUpdate}</span>
          <h2>{t.minutes}</h2>
          <p>{t.syncDesc}</p>
        </div>
      </section>

      <section className="alert-console">
        <div className="section-title">
          <div>
            <h2>{t.consoleTitle}</h2>
            <p>{t.consoleDesc}</p>
          </div>
        </div>

        {alertas.map((alerta) => (
          <div className={`console-alert ${alerta.priority}`} key={alerta.id}>
            <div>
              <strong>{alerta.title}</strong>
              <p>{alerta.body || t.noDescription}</p>
              <small>{t.generated}</small>
            </div>

            <button>{t.review}</button>
          </div>
        ))}
      </section>
    </main>
  );
}

export default Alertas;